---
galaxy_info:
  author: jcfaith
  description: "Joins dc02 to the domain and promotes it to an additional domain controller"
  company: Red Hat
  license: MIT
  min_ansible_version: "2.16"
dependencies: []
