---
galaxy_info:
  author: jcfaith
  description: Authorizes the DHCP server in AD and creates a scope with common options
  company: Red Hat
  license: MIT
  min_ansible_version: "2.16"
dependencies: []
